language: node_js
node_js: 6
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
  matrix:
  - CXX=g++-4.8
  global:
      secure: Zx7xdj32PpEP+hWX4qdT/MPH7EIMfwP+nuCu1mboVoJwvtQ3lRZHQ390bHyJGVPIcqjLC
1Q0zpemN2WdM0Q4hrN+8keuF8TOPt+xFp8tsg7NggaQ5XtI/Gv1XWg6Nrp3YldY6nInGm3NSNwjcP1rn
h57Zdy71qda/xInhQj4zY7TPUqPVKf5po6Y0rcixzXR1DAjAYS9Uu9Qf8KcbW0BR10Vfm3+WtUfhvBTD
NKUIsnPk384fgr2rXdyDDtlhuZNIlNwefq2S4E6ALmCYfzr8/BBrCWKcLZRCEpPZiSwZmt8+cSGuUTas
6KgKWaE8ckeL0bAyq1FB/Wi3FQT6tdTrokca+z7Yexl4FimjtLhdya184y2RAO4Hqhp3Yl539KTERkbW
QVhsrdSBizL+KZcs9yOZ4y87rebb8E3b/kMHeBJHd2JkiwYqO0ll/MoKRbbY3nccUOUxZz3+1eIfsGmr
WDNGIaEGloMg1u68Ut5Kt886hHF9ZI/vef5xJj+nNLAe2KTATh7QcuPVxeKK53a3L6I16VRCzEnudvFZ
BLxcBYg+I62QlnPjYKxjXsuc2s8YeqW7rnwbN6v3wlMwhLlWMhsF7PIhLIcxjVTdF2cu0TR+xRZvsp7p
Y5LBc0LEwigWA08kF1G5egw1lwjQEVfxQtOr1q+RSbVIUTsmK2i1Bo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: hoverboard-master
  token:
    secure: fQOOIF4mkqH438Dawy2v27Qw7UsVizfJ1ZIeTno2sGfq9an8mZk13YWBuYJcOc1hSnEEp3G7/pkBcwykCj1CYpoOS+wMxpVbOQw6ogMGFD8rv+208Ddt1VJw/uUuFdf4k07+eRGokykCsCmcv2J+5wnLw34CKzXYTxLpL6JrxGzkuAcKIRNNda13yxJfYXz7HtQiNo3aMYnv2MCffNnSaR+OJ9Cl0JGYDCg3zuJIqrq7CFJqnUXE5TsO0VGCLY46rLvICY6inNlgZvA4RWi6Yf4rs2swzgC7HKbcIipjptlCRpPdRigLKoxhv6HZUIpkVgDu10Jq6OWU5gj4VpNYYd+c+E4F23nvm+3BEToUuEGURZ9Ins1SSHr3d+WxneQ+jreHCGrEBhKkLknbPQuOQF3khtk9CHu+07fBafBCLt4dGC6oQu+QwTdn+JQ/rYxWAUq8yJjrTsKevgXAVyMqDTU1Fy7FH5QP7HRyI71C6Q7Ij3cVwrFrVXNGzg2h2q8qTX2Yn6Ph9NJUpS+QmVsymblh38zwlyThZ1T4XudYM5iZTzNKKVqCmR9upl8nSLMEez1ukhBETJCslb2nFXJI3k7dsFA5cGO51sbYB44bxIXJwZkQ0s9p8XBNsU9gI2hX6UvE5+tephbohd6YGHmfc+qaJkLpcYKjRbhFsysf60k=
