language: node_js
node_js: 6
cache:
  directories:
  - node_modules
  - bower_components
  - "/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules"
install:
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
deploy:
- provider: firebase
  skip_cleanup: true
  branch: master
  project: hoverboard-firebase
  token:
    secure: SFEDWy0rKbYf5lgSGNlgpF5pnTwczRqaZhqSLdBoFZTieiSXjVRRMou84JEyvVZjbcro1Pxmd9IiKOqpFeu2XNoklT2eXOb1pCBPMiquXbFW1ERVdL70ZVRK+Esr1SkK1yrKjy8N32zLMSkfpqTTcJJQbydt53plQLqx9A98pR8L+2I/Xew/bcjPtMbqVlh9bTYKBGq0LYXJCNMttRvh783wre5olGnKv9r416ghpX/NqEnzGhoiBVg3yLpZJVXLMxhsxWtyusHxz0LSunMbKLtaJbgyqtm1vkJhhl19K7/TQJCe3ELC35ujBSKJ1lVkDIYeldc0/Z8Z8LNq986CpntZMGcLQJyp97nUSJ37IOh4Bzn02UPeDqZfMh60P5Gyug4kGNJYTwL/z4SV6GvdoxOeXa5Gy4PFMyZGYB3DFM8yptEVtbaHIfgHxeCnY5+wdM95aVuMICiT71C8AXUqozjwpIzz68o1f7QsXMgWv55xxkvuLRbPahcli0Qh8IcnU42LfljZLvjAHQE+DpNjk7lvgXxEPD3icIqdmtKnX4R9trUJwLZaSUWEjNyiglg+/Ft2D40pBrlKce4qJlOvrZNKr+lK7t/XXgPjFoX46+cWyDHBo4WUMWtalhEnqR0AvxaF3LRmRZ20n6Xk7OHJwKWdIntI5cmZvf2KXIgxcPc=
